################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_FTY-COMMON-DB "libfty_common_db")
    if (PC_FTY-COMMON-DB_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_FTY-COMMON-DB_CFLAGS} ${PC_FTY-COMMON-DB_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_FTY-COMMON-DB_INCLUDE_HINTS ${PC_FTY-COMMON-DB_INCLUDE_DIRS} ${PC_FTY-COMMON-DB_INCLUDE_DIRS}/*)
        set(PC_FTY-COMMON-DB_LIBRARY_HINTS ${PC_FTY-COMMON-DB_LIBRARY_DIRS} ${PC_FTY-COMMON-DB_LIBRARY_DIRS}/*)
    endif(PC_FTY-COMMON-DB_FOUND)
endif (NOT MSVC)

find_path (
    FTY-COMMON-DB_INCLUDE_DIRS
    NAMES fty_common_db.h
    HINTS ${PC_FTY-COMMON-DB_INCLUDE_HINTS}
)

find_library (
    FTY-COMMON-DB_LIBRARIES
    NAMES libfty_common_db fty-common-db
    HINTS ${PC_FTY-COMMON-DB_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    FTY-COMMON-DB
    REQUIRED_VARS FTY-COMMON-DB_LIBRARIES FTY-COMMON-DB_INCLUDE_DIRS
)
mark_as_advanced(
    FTY-COMMON-DB_FOUND
    FTY-COMMON-DB_LIBRARIES FTY-COMMON-DB_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
