################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_FTY-COMMON-REST "libfty_common_rest")
    if (PC_FTY-COMMON-REST_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_FTY-COMMON-REST_CFLAGS} ${PC_FTY-COMMON-REST_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_FTY-COMMON-REST_INCLUDE_HINTS ${PC_FTY-COMMON-REST_INCLUDE_DIRS} ${PC_FTY-COMMON-REST_INCLUDE_DIRS}/*)
        set(PC_FTY-COMMON-REST_LIBRARY_HINTS ${PC_FTY-COMMON-REST_LIBRARY_DIRS} ${PC_FTY-COMMON-REST_LIBRARY_DIRS}/*)
    endif(PC_FTY-COMMON-REST_FOUND)
endif (NOT MSVC)

find_path (
    FTY-COMMON-REST_INCLUDE_DIRS
    NAMES fty_common_rest.h
    HINTS ${PC_FTY-COMMON-REST_INCLUDE_HINTS}
)

find_library (
    FTY-COMMON-REST_LIBRARIES
    NAMES libfty_common_rest fty-common-rest
    HINTS ${PC_FTY-COMMON-REST_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    FTY-COMMON-REST
    REQUIRED_VARS FTY-COMMON-REST_LIBRARIES FTY-COMMON-REST_INCLUDE_DIRS
)
mark_as_advanced(
    FTY-COMMON-REST_FOUND
    FTY-COMMON-REST_LIBRARIES FTY-COMMON-REST_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
