################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_LIBSASL2 "libsasl2")
    if (PC_LIBSASL2_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_LIBSASL2_CFLAGS} ${PC_LIBSASL2_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_LIBSASL2_INCLUDE_HINTS ${PC_LIBSASL2_INCLUDE_DIRS} ${PC_LIBSASL2_INCLUDE_DIRS}/*)
        set(PC_LIBSASL2_LIBRARY_HINTS ${PC_LIBSASL2_LIBRARY_DIRS} ${PC_LIBSASL2_LIBRARY_DIRS}/*)
    endif(PC_LIBSASL2_FOUND)
endif (NOT MSVC)

find_path (
    LIBSASL2_INCLUDE_DIRS
    NAMES sasl/sasl.h
    HINTS ${PC_LIBSASL2_INCLUDE_HINTS}
)

find_library (
    LIBSASL2_LIBRARIES
    NAMES libsasl2
    HINTS ${PC_LIBSASL2_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    LIBSASL2
    REQUIRED_VARS LIBSASL2_LIBRARIES LIBSASL2_INCLUDE_DIRS
)
mark_as_advanced(
    LIBSASL2_FOUND
    LIBSASL2_LIBRARIES LIBSASL2_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
