################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_TNTNET "tntnet")
    if (PC_TNTNET_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_TNTNET_CFLAGS} ${PC_TNTNET_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_TNTNET_INCLUDE_HINTS ${PC_TNTNET_INCLUDE_DIRS} ${PC_TNTNET_INCLUDE_DIRS}/*)
        set(PC_TNTNET_LIBRARY_HINTS ${PC_TNTNET_LIBRARY_DIRS} ${PC_TNTNET_LIBRARY_DIRS}/*)
    endif(PC_TNTNET_FOUND)
endif (NOT MSVC)

find_path (
    TNTNET_INCLUDE_DIRS
    NAMES tnt/tntnet.h
    HINTS ${PC_TNTNET_INCLUDE_HINTS}
)

find_library (
    TNTNET_LIBRARIES
    NAMES tntnet
    HINTS ${PC_TNTNET_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    TNTNET
    REQUIRED_VARS TNTNET_LIBRARIES TNTNET_INCLUDE_DIRS
)
mark_as_advanced(
    TNTNET_FOUND
    TNTNET_LIBRARIES TNTNET_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
