/*  =========================================================================
    fty_srr_rest_classes - private header file

    Copyright (C) 2014 - 2018 Eaton

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef FTY_SRR_REST_CLASSES_H_INCLUDED
#define FTY_SRR_REST_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/fty-srr-rest.h"

//  Opaque class structures to allow forward references
#ifndef REST_SRR_GET_T_DEFINED
typedef struct _rest_srr_get_t rest_srr_get_t;
#define REST_SRR_GET_T_DEFINED
#endif
#ifndef REST_SRR_SAVE_POST_T_DEFINED
typedef struct _rest_srr_save_post_t rest_srr_save_post_t;
#define REST_SRR_SAVE_POST_T_DEFINED
#endif
#ifndef REST_SRR_RESTORE_POST_T_DEFINED
typedef struct _rest_srr_restore_post_t rest_srr_restore_post_t;
#define REST_SRR_RESTORE_POST_T_DEFINED
#endif
#ifndef REST_SRR_RESET_POST_T_DEFINED
typedef struct _rest_srr_reset_post_t rest_srr_reset_post_t;
#define REST_SRR_RESET_POST_T_DEFINED
#endif

//  Extra headers

//  Internal API

#include "rest_srr_GET.h"
#include "rest_srr_save_POST.h"
#include "rest_srr_restore_POST.h"
#include "rest_srr_reset_POST.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef FTY_SRR_REST_BUILD_DRAFT_API

//  Self test for private classes
FTY_SRR_REST_PRIVATE void
    fty_srr_rest_private_selftest (bool verbose, const char *subtest);

#endif // FTY_SRR_REST_BUILD_DRAFT_API

#endif
